name: AST scan with results as GH codescanning alerts

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  CxONE_GH_code_scanning_alerts:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Checkmarx AST CLI Action
        uses: Checkmarx/ast-github-action@main
        with:
          project_name: covid-ch/CovidCertificate-Management-Service
          base_uri: ${{ secrets.BASE_URI }}
          cx_tenant: ${{ secrets.TENANT }}
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --report-format sarif --scan-types sast,sca,kics --sast-preset-name "ASA Premium"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'cx_result.sarif'
