name: Build, and Sonar analyze then CxONE analyze and put results into Sonar

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  CxONE_and_Sonar:

    runs-on: ubuntu-latest
    if: ${{ true }}

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          
      - name: Checkmarx AST CLI Action
        uses: Checkmarx/ast-github-action@main
        with:
          project_name: covid-ch/CovidCertificate-Management-Service
          base_uri: ${{ secrets.BASE_URI }}
          cx_tenant: ${{ secrets.TENANT }}
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --report-format sonar --scan-types sast --sast-preset-name "ASA Premium" --debug

      

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.4

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: show CxONE results
      - run: |
          cat cx_result_sonar.json

      - name: Analyze (sonar)
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DSonar.organization=covid-ch -Dsonar.projectKey=covid-ch_CovidCertificate-Management-Service -DskipTests -Dsonar.externalIssuesReportPaths=cx_result_sonar.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
          
      
      
  CxONE:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps: 
     - name: Checkout
       uses: actions/checkout@v2
     - name: Checkmarx AST CLI Action
       uses: Checkmarx/ast-github-action@main
       with:
          project_name: covid-ch/CovidCertificate-Management-Service
          base_uri: ${{ secrets.BASE_URI }}
          cx_tenant: ${{ secrets.TENANT }}
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --report-format sonar 
     - name: Sonar CLI Action 
       uses: SonarSource/sonarcloud-github-action@master
       env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
       with:
          args: >
            -Dsonar.externalIssuesReportPaths=cx_result_sonar.json
            -Dsonar.projectKey=covid-ch_CovidCertificate-Management-Service
            -Dsonar.organization=covid-ch
